### ISSUE TITLE
Add skip param on FileItem

### ISSUE THREAD

**Issue by httpdss** [httpdss/struct#19]
FileItem can now skip all files or process all files through the backup strategy. 
i want to be able to set a skip: true flag on the file item structure definition so that individual files can be skipped 

example:
```
structure:
  - README.md:
      skip: true
      content: |
        # AAA
        This is a template repository.
  - script.sh:
      permissions: '0777'
      content: |
        #!/bin/bash
        echo "Hello, WWW!"
```

in this example README.md would be skipped and script.sh would be processed
